---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}
data:
  index.html: |
    <html>
    <h1>Welcome</h1>
    </br>
    <h1>This is a Deployment Change</h1>
    </html